import type { RoleConfig } from '../types'

// Hero content (eyebrow/headline/subtitle/focus/CTAs) is sourced verbatim
// from the human-provided V2 content model (roleModes), mapped onto the
// existing RoleId scheme: software -> software, ai -> machineLearning,
// data -> data, system -> fullJourney. See docs/design/portfolio-v2-design-spec.md §2.2.
export const roles: Record<string, RoleConfig> = {
  software: {
    id: 'software',
    label: 'Software Engineer',
    themeId: 'software',
    hero: {
      eyebrow: 'SENIOR SOFTWARE DEVELOPER • LEAD',
      headline: 'Building reliable software that solves real problems.',
      subtitle:
        'Senior software developer and backend engineering lead with 5+ years of experience building production systems, APIs, databases, integrations, and business-critical applications.',
      focus: [
        'Backend Engineering',
        'Django & REST APIs',
        'System Design',
        'Database Optimization',
        'Third-Party Integrations',
        'Team Leadership',
      ],
      primaryCta: 'Explore My Work',
      primaryCtaTarget: '#projects',
      secondaryCta: 'Download Resume',
      secondaryCtaTarget: 'resume',
    },
    highlightedSkillIds: [
      'python',
      'django',
      'rest',
      'postgresql',
      'docker',
      'git',
      'airflow',
    ],
    highlightedProjectIds: [],
    highlightedMetricIds: [
      'years-experience',
      'deployment-improvement',
      'api-improvement',
      'manual-entry-reduction',
    ],
    experiencePriorityIds: ['shelter-associates', 'swadhar-idwc'],
    resumeVariant: 'software',
    navEmphasis: ['experience', 'skills', 'projects'],
  },
  ai: {
    id: 'ai',
    label: 'AI / ML',
    themeId: 'ai',
    hero: {
      eyebrow: 'MACHINE LEARNING • AI • NLP',
      headline: 'Engineering intelligent systems from data, models, and real-world problems.',
      subtitle:
        'Software engineer with an MS in Machine Learning & Artificial Intelligence, combining production engineering experience with machine learning, NLP, deep learning, and AI research.',
      focus: [
        'Machine Learning',
        'Natural Language Processing',
        'Deep Learning',
        'Generative AI',
        'Explainable AI',
        'MLOps',
      ],
      primaryCta: 'Explore AI Work',
      primaryCtaTarget: '#projects',
      secondaryCta: 'View Research',
      secondaryCtaTarget: '#research',
    },
    highlightedSkillIds: [
      'nlp',
      'machine-learning',
      'deep-learning',
      'llm',
      'mlops',
      'pytorch',
    ],
    highlightedProjectIds: [
      'gesture-recognition',
      'ticket-classification',
      'sentiment-recommendation',
    ],
    highlightedMetricIds: ['years-experience'],
    experiencePriorityIds: ['shelter-associates', 'swadhar-idwc'],
    resumeVariant: 'ai_ml',
    navEmphasis: ['research', 'projects', 'skills'],
  },
  data: {
    id: 'data',
    label: 'Data Analyst',
    themeId: 'data',
    hero: {
      eyebrow: 'DATA • ANALYTICS • ENGINEERING',
      headline: 'Turning data into decisions and measurable impact.',
      subtitle:
        'Experienced in building data pipelines, automating reporting workflows, analyzing operational data, and creating dashboards that help teams understand performance and make better decisions.',
      focus: ['Python', 'SQL', 'ETL', 'Data Pipelines', 'Analytics', 'Dashboards'],
      primaryCta: 'Explore Data Work',
      primaryCtaTarget: '#projects',
      secondaryCta: 'View Impact',
      secondaryCtaTarget: '#metrics',
    },
    highlightedSkillIds: [
      'sql',
      'pandas',
      'excel',
      'superset',
      'metabase',
      'airflow',
      'etl',
    ],
    highlightedProjectIds: [],
    highlightedMetricIds: [
      'reporting-time-reduction',
      'data-accuracy',
      'survey-forms',
      'program-teams',
    ],
    experiencePriorityIds: ['swadhar-idwc', 'shelter-associates'],
    resumeVariant: 'data_analyst',
    navEmphasis: ['experience', 'skills', 'projects'],
  },
  system: {
    id: 'system',
    label: 'System View',
    themeId: 'system',
    hero: {
      eyebrow: 'SOFTWARE → DATA → ML → AI',
      headline: "A software engineer's journey into intelligent systems.",
      subtitle:
        'My career has evolved from software development and backend engineering into data, machine learning, NLP, and AI while staying grounded in building practical production systems.',
      focus: [
        'Software Engineering',
        'Backend Systems',
        'Data',
        'Machine Learning',
        'NLP',
        'Artificial Intelligence',
      ],
      primaryCta: 'Explore My Journey',
      primaryCtaTarget: '#projects',
      secondaryCta: 'Download Resume',
      secondaryCtaTarget: 'resume',
    },
    highlightedSkillIds: [],
    highlightedProjectIds: [
      'gesture-recognition',
      'ticket-classification',
      'sentiment-recommendation',
    ],
    highlightedMetricIds: ['years-experience'],
    experiencePriorityIds: ['shelter-associates', 'swadhar-idwc'],
    resumeVariant: 'software',
    navEmphasis: ['experience', 'research', 'projects', 'skills'],
  },
}
